name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.REPO_USERNAME }}
        password: ${{ secrets.REPO_PASSWORD }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag dimitrivdw/comfortcloud2mqtt
    - name: Push the Docker image
      run: docker push dimitrivdw/comfortcloud2mqtt 
